import SwiftSyntax
import SwiftSyntaxBuilder

// MARK: - Tool syntax support

/// Adds the protocol conformance generated by a schema macro.
package func conformanceExtension(
    of type: some TypeSyntaxProtocol,
    to protocolName: String
) -> [ExtensionDeclSyntax] {
    let expanded: DeclSyntax = "nonisolated extension \(raw: type.trimmedDescription): \(raw: protocolName) {}"
    return expanded.as(ExtensionDeclSyntax.self).map { [$0] } ?? []
}

/// Returns the access prefix needed by a generated member of `declaration`.
package func accessPrefix(of modifiers: DeclModifierListSyntax) -> String {
    modifiers.first { $0.name.text == "public" || $0.name.text == "package" }
        .map { "\($0.name.text) " } ?? ""
}

/// A stored property as `@MainArgument` and `@ReferArgument` see it.
package struct ToolProperty {
    package let name: String
    /// Type name with every level of `Optional` removed.
    package let baseTypeName: String
    package let isOptional: Bool
    package let argument: ToolArgument?
}

/// The stored properties described by a struct schema macro.
package func storedProperties(of structDecl: StructDeclSyntax) -> [ToolProperty] {
    structDecl.memberBlock.members.compactMap { member in
        guard let varDecl = member.decl.as(VariableDeclSyntax.self),
              varDecl.bindingSpecifier.tokenKind == .keyword(.let)
                  || varDecl.bindingSpecifier.tokenKind == .keyword(.var),
              let binding = varDecl.bindings.first,
              binding.accessorBlock == nil,
              let pattern = binding.pattern.as(IdentifierPatternSyntax.self),
              let declared = binding.typeAnnotation?.type.trimmedDescription,
              !varDecl.modifiers.contains(where: { $0.name.tokenKind == .keyword(.static) })
        else {
            return nil
        }

        let baseTypeName = optionTypeName(declared)
        return ToolProperty(
            name: pattern.identifier.text,
            baseTypeName: baseTypeName,
            isOptional: baseTypeName != declared,
            argument: ToolArgument(attributes: varDecl.attributes)
        )
    }
}

package struct MacroError: Error, CustomStringConvertible {
    package let message: String

    package init(_ message: String) { self.message = message }

    package var description: String { message }
}
