import SwiftSyntax
import SwiftSyntaxBuilder

// MARK: - Schema source

/// A JSON Schema expressed as Swift source, written as `BaseType` literals that break over several
/// lines once they get wide. The `ArgumentSchema` member is a `[String: BaseType]` dictionary.
package indirect enum SchemaSource {
    /// Verbatim source: a literal (`1`, `"email"`), a forwarded macro argument, or `Type.ArgumentSchema`.
    case literal(String)
    case dictionary([(key: String, value: SchemaSource)])
    case array([SchemaSource])

    /// The one-line form, or `nil` when any part of it is already written across several lines.
    package func flattened() -> String? {
        switch self {
        case .literal(let source):
            return source.contains("\n") ? nil : source
        case .array(let elements):
            let parts = elements.compactMap { $0.flattened() }
            return parts.count == elements.count ? "[" + parts.joined(separator: ", ") + "]" : nil
        case .dictionary(let entries):
            let parts = entries.compactMap { entry in
                entry.value.flattened().map { "\(String(reflecting: entry.key)): \($0)" }
            }
            guard parts.count == entries.count else { return nil }
            return parts.isEmpty ? "[:]" : "[" + parts.joined(separator: ", ") + "]"
        }
    }

    /// - Parameter indent: the column the first character of this value is written at.
    package func rendered(indent: Int) -> String {
        // Write one line when it stays within the 100 columns the surrounding code is kept to.
        if let inline = flattened(), indent + inline.count <= 100 { return inline }
        let pad = String(repeating: " ", count: indent)
        let innerPad = String(repeating: " ", count: indent + 4)
        switch self {
        case .literal(let source):
            return source
        case .array(let elements):
            guard !elements.isEmpty else { return "[]" }
            return "[\n" + elements.map { "\(innerPad)\($0.rendered(indent: indent + 4))" }.joined(separator: ",\n")
                + "\n\(pad)]"
        case .dictionary(let entries):
            guard !entries.isEmpty else { return "[:]" }
            return "[\n" + entries.map {
                "\(innerPad)\(String(reflecting: $0.key)): \($0.value.rendered(indent: indent + 4))"
            }.joined(separator: ",\n") + "\n\(pad)]"
        }
    }
}

/// The generated `ArgumentSchema` member: the schema literal with `extra` merged over it when supplied.
/// `additionalProperties` is forced back to `false` after that merge.
package func argumentSchemaMember(
    access: String,
    schema: SchemaSource,
    extra: String? = nil
) -> DeclSyntax {
    // An omitted `extra` reaches here as nothing at all or as `[:]`, neither of which merges anything.
    let extra = extra.flatMap { source -> String? in
        let written = source.filter { !$0.isWhitespace }
        return written.isEmpty || written == "[:]" ? nil : source
    }
    var lines: [String] = []
    if let extra {
        lines.append("var schema: [String: BaseType] = \(schema.rendered(indent: 4))")
        lines.append("schema.merge(\(extra)) { _, new in new }")
        lines.append("schema[\"additionalProperties\"] = false")
        lines.append("return schema")
    }
    let body: String
    if lines.isEmpty {
        body = schema.rendered(indent: 4)
    } else {
        body = lines.enumerated().map { $0.offset == 0 ? $0.element : "    \($0.element)" }.joined(separator: "\n")
    }
    let member: DeclSyntax = """
        \(raw: access)static var ArgumentSchema: [String: BaseType] {
            \(raw: body)
        }
        """
    return member
}

// MARK: - Schema builder

/// Infers the schema of a Swift type name: scalars, `Optional`, arrays of either, and any other
/// type. A macro only sees the declaration it is attached to, so any other named type is assumed to own
/// an `ArgumentSchema` generated by one of the schema macros, which is inlined, and a named type without
/// one fails to compile on the missing member. A property that should use `$ref` instead of inlining
/// the named type has to say so with `@ReferToolArgument`.
package func inferredSchema(forTypeName typeName: String) -> SchemaSource {
    let base = optionTypeName(typeName)
    if let element = arrayElementTypeName(base) {
        return .dictionary([
            ("type", .literal("\"array\"")), ("items", inferredSchema(forTypeName: element)),
        ])
    }
    if let jsonType = scalarType(base) {
        return .dictionary([("type", .literal("\"\(jsonType)\""))])
    }
    // `ArgumentSchema` is a dictionary, so it has to be boxed to sit inside another schema.
    return .literal(".dict(\(base).ArgumentSchema)")
}

/// The entries of the `object` a list of stored properties describes, without the definitions it
/// references: the JSON type, `properties`, `required` and `additionalProperties`.
package func objectEntries(of properties: [ToolProperty]) -> [(key: String, value: SchemaSource)] {
    [
        ("type", .literal("\"object\"")),
        ("properties", .dictionary(properties.map {
            (key: $0.name, value: valueSchema(typeName: $0.baseTypeName, argument: $0.argument))
        })),
        ("required", .array(properties.filter { !$0.isOptional }.map {
            .literal(String(reflecting: $0.name))
        })),
        ("additionalProperties", .literal("false")),
    ]
}

/// The object schema for a struct. A root schema includes the `$def` definitions it references; a
/// `@ReferArgument` definition does not, because its enclosing root collects them.
package func objectSchema(
    of properties: [ToolProperty],
    includesDefinitions: Bool = true
) -> SchemaSource {
    var entries = objectEntries(of: properties)
    if includesDefinitions,
       let definitions = referencedDefinitionsSchema(of: properties.map { ($0.baseTypeName, $0.argument) }) {
        entries.append(("$def", definitions))
    }
    return .dictionary(entries)
}

/// Schema of one value: the marker decides the JSON type and its constraints, otherwise the Swift type
/// is used.
package func valueSchema(typeName: String, argument: ToolArgument?) -> SchemaSource {
    guard let argument else { return inferredSchema(forTypeName: typeName) }
    switch argument.kind {
    case .string: return StringToolArgumentMacro.schema(typeName: typeName, argument)
    case .number: return NumberToolArgumentMacro.schema(typeName: typeName, argument)
    case .boolean: return BooleanToolArgumentMacro.schema(typeName: typeName, argument)
    case .array: return ArrayToolArgumentMacro.schema(typeName: typeName, argument)
    case .reference: return ReferToolArgumentMacro.schema(typeName: typeName, argument)
    }
}
