//
//  SchemaProtocol.swift
//  SimpleOpenAIKit
//
//  Created by snowscattered on 2026/10/4.
//

import Foundation
import SimpleOpenAIKitMacro

/// A structured output shape expressed as a type instead of a hand-written JSON schema.
///
/// `@MainArgument` generates every member this protocol asks for, so declaring the conformance on the
/// tool argument macro is the only thing left to write:
///
/// ```swift
/// @MainArgument(description: "Fetch the weather for a given location.", strict: true)
/// struct Weather: SchemaProtocol { ... }
/// ```
///
/// `Weather` is then both the schema and the type the response decodes into, and constraining a
/// response is a single declaration: `ChatResponseFormat(Weather.self)`,
/// `ResponseFormatTextConfig(Weather.self)`, `MessageJSONOutputFormat(Weather.self)`.
/// Unlike `ToolProtocol` there is nothing to call: the provider returns the JSON and the caller
/// decodes it into the type itself. One macro, one type and one schema cover both a tool and a
/// structured output: the `MainArgument` conformance `@MainArgument` adds is the same one a tool
/// argument carries, and the metadata it writes is prefixed `__`, so it never shadows the properties
/// of the payload or the `name`, `description` and `strict` a tool declares for itself.
public protocol SchemaProtocol: Codable & Sendable {
    /// The JSON Schema the answer is validated against, generated by `@MainArgument` from the stored
    /// properties of the struct that is also the payload type.
    static var ArgumentSchema: [String: BaseType] { get }
    /// The name reported to the provider next to the schema; `@MainArgument` takes it from the type.
    static var __name: String { get }
    /// Model-facing description of what the output represents.
    static var __description: String? { get }
    /// Force the provider to follow the schema exactly; `nil` keeps the provider default.
    static var __strict: Bool? { get }
}

public extension ChatResponseFormat {
    /// Build the OpenAI Chat Completions `response_format` from a `SchemaProtocol` type.
    init<T: SchemaProtocol>(_: T.Type) {
        self = .json_schema(.init(json_schema: .init(
            name: T.__name,
            description: T.__description,
            schema: T.ArgumentSchema,
            strict: T.__strict
        )))
    }
}
public extension ResponseFormatTextConfig {
    /// Build the OpenAI Responses `text.format` from a `SchemaProtocol` type.
    init<T: SchemaProtocol>(_: T.Type) {
        self = .json_schema(.init(
            name: T.__name,
            description: T.__description,
            schema: T.ArgumentSchema,
            strict: T.__strict
        ))
    }
}
public extension MessageJSONOutputFormat {
    /// Build the Anthropic Messages `output_config.format` from a `SchemaProtocol` type.
    /// Anthropic only carries the schema itself, so `__name`, `__description` and `__strict` are
    /// dropped.
    init<T: SchemaProtocol>(_: T.Type) {
        self = .init(schema: T.ArgumentSchema)
    }
}
