//
//  ToolArgumentProtocol.swift
//  SimpleOpenAIKit
//
//  Created by snow on 9/6/26.
//

import SimpleCodableMacro

/// A type that can describe itself as a JSON Schema fragment.
public protocol ArgumentSchema: Codable & Sendable {
    static var ArgumentSchema: [String: BaseType] { get }
}
/// Serialises the schema rather than a value, so a schema constant encodes to its own description.
public extension ArgumentSchema {
    func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(Self.ArgumentSchema)
    }
}

/// The root argument object of a tool; carries the `object` schema `@MainArgument` generates.
public protocol MainArgument: ArgumentSchema {}
/// A `$def` entry that a root schema references through `@ReferToolArgument`.
public protocol ReferArgument: ArgumentSchema {}
/// An enum whose schema is the list of its raw values, generated by `@EnumToolArgument`.
public protocol EnumArgument: Codable & Sendable {
    static var ArgumentSchema: [String: BaseType] { get }
}
public extension EnumArgument {
    /// Serialises the schema rather than a value.
    func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(Self.ArgumentSchema)
    }
}
/// An enum whose schema is `anyOf` over its cases, generated by `@AnyOfToolArgument`.
public protocol AnyOfArgument: Codable & Sendable {
    static var ArgumentSchema: [String: BaseType] { get }
}
public extension AnyOfArgument {
    /// Serialises the schema rather than a value.
    func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(Self.ArgumentSchema)
    }
}
